In [57]:
import pandas as pd
import numpy as np


In [58]:
data=pd.read_csv("./dataset/fifa.csv")

In [59]:
data

Unnamed: 0      ID                Name  Age   
0               0  158023            L. Messi   31  \
1               1   20801   Cristiano Ronaldo   33   
2               2  190871           Neymar Jr   26   
3               3  193080              De Gea   27   
4               4  192985        K. De Bruyne   27   
...           ...     ...                 ...  ...   
18202       18202  238813        J. Lundstram   19   
18203       18203  243165  N. Christoffersson   19   
18204       18204  241638           B. Worman   16   
18205       18205  246268      D. Walker-Rice   17   
18206       18206  246269           G. Nugent   16   

                                                Photo Nationality   
0      https://cdn.sofifa.org/players/4/19/158023.png   Argentina  \
1       https://cdn.sofifa.org/players/4/19/20801.png    Portugal   
2      https://cdn.sofifa.org/players/4/19/190871.png      Brazil   
3      https://cdn.sofifa.org/players/4/19/193080.png       Spain   
4      https://cdn.sofifa.org/players/4/19/192985.png     Belgium   
...                                               ...         ...   
18202  https://cdn.sofifa.org/players/4/19/238813.png     England   
18203  https://cdn.sofifa.org/players/4/19/243165.png      Sweden   
18204  https://cdn.sofifa.org/players/4/19/241638.png     England   
18205  https://cdn.sofifa.org/players/4/19/246268.png     England   
18206  https://cdn.sofifa.org/players/4/19/246269.png     England   

                                      Flag  Overall  Potential   
0      https://cdn.sofifa.org/flags/52.png       94         94  \
1      https://cdn.sofifa.org/flags/38.png       94         94   
2      https://cdn.sofifa.org/flags/54.png       92         93   
3      https://cdn.sofifa.org/flags/45.png       91         93   
4       https://cdn.sofifa.org/flags/7.png       91         92   
...                                    ...      ...        ...   
18202  https://cdn.sofifa.org/flags/14.png       47         65   
18203  https://cdn.sofifa.org/flags/46.png       47         63   
18204  https://cdn.sofifa.org/flags/14.png       47         67   
18205  https://cdn.sofifa.org/flags/14.png       47         66   
18206  https://cdn.sofifa.org/flags/14.png       46         66   

                      Club  ... Composure Marking StandingTackle   
0             FC Barcelona  ...      96.0    33.0           28.0  \
1                 Juventus  ...      95.0    28.0           31.0   
2      Paris Saint-Germain  ...      94.0    27.0           24.0   
3        Manchester United  ...      68.0    15.0           21.0   
4          Manchester City  ...      88.0    68.0           58.0   
...                    ...  ...       ...     ...            ...   
18202      Crewe Alexandra  ...      45.0    40.0           48.0   
18203       Trelleborgs FF  ...      42.0    22.0           15.0   
18204     Cambridge United  ...      41.0    32.0           13.0   
18205      Tranmere Rovers  ...      46.0    20.0           25.0   
18206      Tranmere Rovers  ...      43.0    40.0           43.0   

       SlidingTackle GKDiving  GKHandling  GKKicking  GKPositioning   
0               26.0      6.0        11.0       15.0           14.0  \
1               23.0      7.0        11.0       15.0           14.0   
2               33.0      9.0         9.0       15.0           15.0   
3               13.0     90.0        85.0       87.0           88.0   
4               51.0     15.0        13.0        5.0           10.0   
...              ...      ...         ...        ...            ...   
18202           47.0     10.0        13.0        7.0            8.0   
18203           19.0     10.0         9.0        9.0            5.0   
18204           11.0      6.0         5.0       10.0            6.0   
18205           27.0     14.0         6.0       14.0            8.0   
18206           50.0     10.0        15.0        9.0           12.0   

      GKReflexes Release Clause  
0            8.0        €226.5M 

In [60]:
data['Nationality'].unique()

array(['Argentina', 'Portugal', 'Brazil', 'Spain', 'Belgium', 'Croatia',
       'Uruguay', 'Slovenia', 'Poland', 'Germany', 'France', 'England',
       'Italy', 'Egypt', 'Colombia', 'Denmark', 'Gabon', 'Wales',
       'Senegal', 'Costa Rica', 'Slovakia', 'Netherlands',
       'Bosnia Herzegovina', 'Morocco', 'Serbia', 'Algeria', 'Austria',
       'Greece', 'Chile', 'Sweden', 'Korea Republic', 'Finland', 'Guinea',
       'Montenegro', 'Armenia', 'Switzerland', 'Norway', 'Czech Republic',
       'Scotland', 'Ghana', 'Central African Rep.', 'DR Congo',
       'Ivory Coast', 'Russia', 'Ukraine', 'Iceland', 'Mexico', 'Jamaica',
       'Albania', 'Venezuela', 'Japan', 'Turkey', 'Ecuador', 'Paraguay',
       'Mali', 'Nigeria', 'Cameroon', 'Dominican Republic', 'Israel',
       'Kenya', 'Hungary', 'Republic of Ireland', 'Romania',
       'United States', 'Cape Verde', 'Australia', 'Peru', 'Togo',
       'Syria', 'Zimbabwe', 'Angola', 'Burkina Faso', 'Iran', 'Estonia',
       'Tunisia', 'Equato

In [61]:
def nation(x):
    if x=='England' or x=='Germany' or x=='Spain' or x=='Argentina' or x=='France':
        return x
    else: 
        return 'others'

In [62]:
data['Nationality']=data['Nationality'].apply(nation)

In [63]:
data['Nationality'].unique()

array(['Argentina', 'others', 'Spain', 'Germany', 'France', 'England'],
      dtype=object)

In [64]:
data['Age'].unique()

array([31, 33, 26, 27, 32, 25, 29, 28, 24, 30, 19, 40, 22, 23, 34, 35, 36,
       37, 21, 18, 20, 39, 41, 17, 38, 45, 42, 16, 44], dtype=int64)

In [65]:
def age(x):
    if x>16 and x<30:
        return "16-30"
    elif x>30 and x<40:
        return "30-40"
    else:
        return "above 40"

In [66]:
data['AgeClass']=data['Age'].apply(age)
data['AgeClass']

0           30-40
1           30-40
2           16-30
3           16-30
4           16-30
           ...   
18202       16-30
18203       16-30
18204    above 40
18205       16-30
18206    above 40
Name: AgeClass, Length: 18207, dtype: object

In [67]:
from sklearn.preprocessing import LabelEncoder


In [68]:
le=LabelEncoder()
data['Nationality']=le.fit_transform(data['Nationality'])

In [69]:
data['Nationality'].unique()

array([0, 5, 4, 3, 2, 1])

In [70]:
data.head()

Unnamed: 0      ID               Name  Age   
0           0  158023           L. Messi   31  \
1           1   20801  Cristiano Ronaldo   33   
2           2  190871          Neymar Jr   26   
3           3  193080             De Gea   27   
4           4  192985       K. De Bruyne   27   

                                            Photo  Nationality   
0  https://cdn.sofifa.org/players/4/19/158023.png            0  \
1   https://cdn.sofifa.org/players/4/19/20801.png            5   
2  https://cdn.sofifa.org/players/4/19/190871.png            5   
3  https://cdn.sofifa.org/players/4/19/193080.png            4   
4  https://cdn.sofifa.org/players/4/19/192985.png            5   

                                  Flag  Overall  Potential   
0  https://cdn.sofifa.org/flags/52.png       94         94  \
1  https://cdn.sofifa.org/flags/38.png       94         94   
2  https://cdn.sofifa.org/flags/54.png       92         93   
3  https://cdn.sofifa.org/flags/45.png       91         93   
4   https://cdn.sofifa.org/flags/7.png       91         92   

                  Club  ... Marking StandingTackle SlidingTackle  GKDiving   
0         FC Barcelona  ...    33.0           28.0          26.0       6.0  \
1             Juventus  ...    28.0           31.0          23.0       7.0   
2  Paris Saint-Germain  ...    27.0           24.0          33.0       9.0   
3    Manchester United  ...    15.0           21.0          13.0      90.0   
4      Manchester City  ...    68.0           58.0          51.0      15.0   

  GKHandling  GKKicking  GKPositioning  GKReflexes Release Clause AgeClass  
0       11.0       15.0           14.0         8.0        €226.5M    30-40  
1       11.0       15.0           14.0        11.0        €127.1M    30-40  
2        9.0       15.0           15.0        11.0        €228.1M    16-30  
3       85.0       87.0           88.0        94.0        €138.6M    16-30  
4       13.0        5.0           10.0        13.0        €196.4M    16-30  

[5 rows x 90 columns]

# Feature Mapping
- A feature mapping is a function which maps a data vector to a feature space


In [71]:
ds=pd.read_csv("./dataset/bigmart.csv")
ds

Item_Identifier  Item_Weight Item_Fat_Content  Item_Visibility   
0              FDA15        9.300          Low Fat         0.016047  \
1              DRC01        5.920          Regular         0.019278   
2              FDN15       17.500          Low Fat         0.016760   
3              FDX07       19.200          Regular         0.000000   
4              NCD19        8.930          Low Fat         0.000000   
...              ...          ...              ...              ...   
8518           FDF22        6.865          Low Fat         0.056783   
8519           FDS36        8.380          Regular         0.046982   
8520           NCJ29       10.600          Low Fat         0.035186   
8521           FDN46        7.210          Regular         0.145221   
8522           DRG01       14.800          Low Fat         0.044878   

                  Item_Type  Item_MRP Outlet_Identifier   
0                     Dairy  249.8092            OUT049  \
1               Soft Drinks   48.2692            OUT018   
2                      Meat  141.6180            OUT049   
3     Fruits and Vegetables  182.0950            OUT010   
4                 Household   53.8614            OUT013   
...                     ...       ...               ...   
8518            Snack Foods  214.5218            OUT013   
8519           Baking Goods  108.1570            OUT045   
8520     Health and Hygiene   85.1224            OUT035   
8521            Snack Foods  103.1332            OUT018   
8522            Soft Drinks   75.4670            OUT046   

      Outlet_Establishment_Year Outlet_Size Outlet_Location_Type   
0                          1999      Medium               Tier 1  \
1                          2009      Medium               Tier 3   
2                          1999      Medium               Tier 1   
3                          1998         NaN               Tier 3   
4                          1987        High               Tier 3   
...                         ...         ...                  ...   
8518                       1987        High               Tier 3   
8519                       2002         NaN               Tier 2   
8520                       2004       Small               Tier 2   
8521                       2009      Medium               Tier 3   
8522                       1997       Small               Tier 1   

            Outlet_Type  Item_Outlet_Sales  
0     Supermarket Type1          3735.1380  
1     Supermarket Type2           443.4228  
2     Supermarket Type1          2097.2700  
3         Grocery Store           732.3800  
4     Supermarket Type1           994.7052  
...                 ...                ...  
8518  Supermarket Type1          2778.3834  
8519  Supermarket Type1           549.2850  
8520  Supermarket Type1          1193.1136  
8521  Supermarket Type2          1845.5976  
8522  Supermarket Type1           765.6700  

[8523 rows x 12 columns]

In [72]:
ds["Outlet_Size"]=ds["Outlet_Size"].fillna(ds['Outlet_Size'].mode()[0])

In [73]:
ds.isnull().sum()

Item_Identifier                 0
Item_Weight                  1463
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                     0
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

In [74]:
ds['Outlet_Size'].unique()


array(['Medium', 'High', 'Small'], dtype=object)

In [75]:
ds['Outlet_Size']=ds['Outlet_Size'].replace(("High","Medium","Small"),(1,2,3))

In [76]:
ds['Outlet_Size'].unique()


array([2, 1, 3], dtype=int64)

# One Hot Encoding
- we map each category to a vector that contains 1 or 0. The number of vectors on the number of categories
- e.g. if we have 3 categories (a, b, c) and we have 2 observations (x, y) then x will be encoded as [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
- x and y will be encoded as [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
- the specific vectors can be computed algorithmically with statistic tools like patsy
- onehot is just a particular way to construct a design matrix

In [77]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder()
feature=ohe.fit_transform(ds[['Outlet_Type']]).toarray()
feature

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       ...,
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.]])

2 cat               ->            label encoding
multiple features   ->            onehot encoding


In [78]:
ds['Item_Fat_Content'].unique()

array(['Low Fat', 'Regular', 'low fat', 'LF', 'reg'], dtype=object)

In [81]:
pd.get_dummies(ds=ds,columns=['Item_Fat_Content'],drop_first=True)

TypeError: get_dummies() got an unexpected keyword argument 'ds'

In [83]:
ds.head()

Item_Identifier  Item_Weight Item_Fat_Content  Item_Visibility   
0           FDA15         9.30          Low Fat         0.016047  \
1           DRC01         5.92          Regular         0.019278   
2           FDN15        17.50          Low Fat         0.016760   
3           FDX07        19.20          Regular         0.000000   
4           NCD19         8.93          Low Fat         0.000000   

               Item_Type  Item_MRP Outlet_Identifier   
0                  Dairy  249.8092            OUT049  \
1            Soft Drinks   48.2692            OUT018   
2                   Meat  141.6180            OUT049   
3  Fruits and Vegetables  182.0950            OUT010   
4              Household   53.8614            OUT013   

   Outlet_Establishment_Year  Outlet_Size Outlet_Location_Type   
0                       1999            2               Tier 1  \
1                       2009            2               Tier 3   
2                       1999            2               Tier 1   
3                       1998            2               Tier 3   
4                       1987            1               Tier 3   

         Outlet_Type  Item_Outlet_Sales  
0  Supermarket Type1          3735.1380  
1  Supermarket Type2           443.4228  
2  Supermarket Type1          2097.2700  
3      Grocery Store           732.3800  
4  Supermarket Type1           994.7052

# Feature Scaling

- X_train = (X_train - X_train.mean()) / X_train.std()
- two methods of feature scaling
    1. standardization: (Used to scale the  values)
            it's the process of rescaling one or more attributes so that they hae an mean value of 0 and
            a standard deviation of 1.
    2. Normalization:
            Its used to change the valyes of numerics columns in the dataset to yse a common scale, without distorting differences
            in the range of the values.


# 20% for testing 80% for train (data split)


# Regression models                                     
1.  Linear Regression    (simple, multi)                                                          
2.  Decision Tree Regression                            
3.  Random Forest Regression                           
4.  Support Vector Regression   

# Classfication Models
1. Logistic Regression
2. Support Vector classification
3. Naive-Bayes
4. KNN