In [46]:
import numpy as np

a=[[[1,3,4,6,7,5,10,12,15,18,21,2,22,33,11,10]]]
print(np.ndim(a))
print(f"a_type= {type(a)}")
arr=np.array(a)
print(f"arr_type= {type(arr)}")
print(f"arr= {arr}")

3
a_type= <class 'list'>
arr_type= <class 'numpy.ndarray'>
arr= [[[ 1  3  4  6  7  5 10 12 15 18 21  2 22 33 11 10]]]


In [47]:
print(arr.reshape(4,4))

[[ 1  3  4  6]
 [ 7  5 10 12]
 [15 18 21  2]
 [22 33 11 10]]


In [52]:
np.shape(arr)

(1, 1, 16)

In [57]:
ar=np.arange(1,20,5)
ar

array([ 1,  6, 11, 16])

In [62]:
a = np.linspace(1,5,10)
a

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])